---
- name: Add Elasticsearch public key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add Logstash repository
  apt_repository: repo='deb http://packages.elasticsearch.org/logstash/1.5/debian stable main' state=present update_cache=yes

- name: Install Logstash
  apt: name=logstash state=present force=yes update_cache=yes cache_valid_time=300
