---
- name: Add PackageCloud public key
  apt_key: url=https://packagecloud.io/gpg.key state=present

- name: Add PackageCloud repository
  apt_repository: repo='deb https://packagecloud.io/grafana/stable/debian/ wheezy main' state=present update_cache=yes

- name: Install Grafana
  apt: name=grafana state=present

- name: Configure Grafana
  template: src=grafana.ini.j2 dest=/etc/grafana/grafana.ini owner=root group=root mode=0644

- name: Start Grafana service
  service: name=grafana-server state=started enabled=yes
