---
- name: Find current version
  shell: readlink /opt/kibana | cut -c 13-
  changed_when: no
  register: current_kibana_version

- name: Download Kibana archive
  get_url:
    url=https://download.elastic.co/kibana/kibana/kibana-{{ kibana.version }}.tar.gz
    dest=/opt
    owner={{ kibana.user }} group={{ kibana.user }}
  register: new_archive_downloaded
  when: current_kibana_version.stdout != kibana.version

- name: Decompress archive
  unarchive:
    src=/opt/kibana-{{ kibana.version }}.tar.gz
    dest=/opt copy=no
    owner={{ kibana.user }} group={{ kibana.user }}
  when: current_kibana_version.stdout != kibana.version or new_archive_downloaded|changed

- name: Uncompressed Kibana linked to path
  file:
    src=/opt/kibana-{{ kibana.version }}
    path=/opt/kibana state=link
    owner={{ kibana.user }} group={{ kibana.user }}
  when: current_kibana_version.stdout != kibana.version or new_archive_downloaded|changed

- name: Set permissions
  file: path=/opt/kibana-{{ kibana.version }} state=directory owner={{ kibana.user }} group={{ kibana.user }} recurse=yes
  changed_when: False

- name: Configure Kibana supervisor
  template: src=supervisord.conf.j2 dest=/etc/supervisor/conf.d/kibana.conf owner=root group=root mode=644
  notify: Update supervisor