---
- name: Add Elasticsearch public key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add Elasticsearch repository
  apt_repository: "repo='deb http://packages.elasticsearch.org/elasticsearch/{{ elasticsearch.version }}/debian stable main' state=present update_cache=yes"

- name: Install Elasticsearch
  apt: name=elasticsearch state=latest update_cache=yes cache_valid_time=8600

- name: Configure Elasticsearch
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644

- name: Start Elasticsearch service
  service: name=elasticsearch state=started enabled=yes

- name: Configure Elasticsearch supervisor
  template: src=supervisord.conf.j2 dest=/etc/supervisor/conf.d/elasticsearch.conf owner=root group=root mode=0644
  notify: Update supervisord

- name: Ensure Pip is installed
  apt: name=python-pip state=installed

- name: Install Elasticsearch Curator and dependencies
  pip: "name={{ item }}"
  with_items:
    - elasticsearch-curator
    - argparse

- name: Configure Elasticsearch Curator cron jobs
  cron:
    name:    "{{ item.name }}"
    job:     "{{ item.job  }}"
    minute:  "{{ item.minute  | default('*') }}"
    hour:    "{{ item.hour    | default('*') }}"
    day:     "{{ item.day     | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    month:   "{{ item.month   | default('*') }}"
  with_items: elasticsearch_curator.crons
